[package]
name = "librustsnowgem"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]

[lib]
name = "rustsnowgem"
path = "src/rustsnowgem.rs"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
