[package]
name = "librustvidulum"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]

[lib]
name = "rustvidulum"
path = "src/rustvidulum.rs"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
